package net.meh.cosmolib.furniture.layout;

import com.google.gson.*;
import net.minecraft.core.BlockPos;
import org.jetbrains.annotations.Nullable;

import java.util.*;
import java.util.stream.Collectors;

/**
 * Data class that holds the hitbox layout for a multi-block furniture piece.
 *
 * <h3>Coordinate system</h3>
 * All positions are relative to the anchor block (always at {@link BlockPos#ZERO}).
 * The anchor is always included in the position lists (it is the root furniture block).
 * Only occupied positions are stored — empty space is not represented.
 *
 * <h3>Straight vs diagonal</h3>
 * <ul>
 *   <li><b>Straight</b> — rotations 0, 2, 4, 6 (N / E / S / W).</li>
 *   <li><b>Diagonal</b> — rotations 1, 3, 5, 7 (NE / SE / SW / NW).</li>
 * </ul>
 * When {@link #diagonalAutoGenerated} is {@code true}, the diagonal list was
 * copied from the straight list (valid when width == depth, i.e. the footprint
 * is symmetric).
 *
 * <h3>Usage</h3>
 * <pre>{@code
 * // Symmetric layout — diagonal is auto-generated
 * MultiBlockLayout layout = MultiBlockLayout.of("my_fountain",
 *         List.of(new BlockPos(0,0,0), new BlockPos(1,0,0), new BlockPos(0,0,1), new BlockPos(1,0,1)));
 *
 * // Explicit diagonal
 * MultiBlockLayout layout = MultiBlockLayout.of("ancient_arbor", straightPositions, diagonalPositions);
 * }</pre>
 */
public final class MultiBlockLayout {

    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

    // ------------------------------------------------------------------
    // Fields
    // ------------------------------------------------------------------

    private final String furnitureId;
    /** [width, height, depth] computed from straight positions. */
    private final int[] bounds;
    private final List<BlockPos> straightPositions;
    /**
     * Null when the diagonal was auto-generated from straight ({@link #diagonalAutoGenerated} = true).
     * {@link #getRotatedPositions} falls back to straightPositions in that case.
     */
    @Nullable
    private final List<BlockPos> diagonalPositions;
    private final boolean diagonalAutoGenerated;

    /**
     * Subset of {@link #straightPositions} that should use a slab (half-height) hitbox.
     * Empty list = no slab positions.
     */
    private final List<BlockPos> straightSlabPositions;

    /**
     * Null when slab-diagonal is auto-generated from {@link #straightSlabPositions}.
     * {@link #getSlabPositions} falls back to straightSlabPositions in that case.
     */
    @Nullable
    private final List<BlockPos> diagonalSlabPositions;

    /**
     * Subset of {@link #straightPositions} whose blocks spawn a
     * {@link net.meh.cosmolib.entity.SeatEntity} on right-click.
     * Empty list = no seat positions.
     */
    private final List<BlockPos> straightSeatPositions;

    /** Diagonal seat positions, or {@code null} when auto-generated from straight. */
    @Nullable
    private final List<BlockPos> diagonalSeatPositions;

    /**
     * Height (in blocks) at which the {@link net.meh.cosmolib.entity.SeatEntity}
     * spawns above each seat position's origin.  {@code 5/16} by default (matches
     * {@link net.meh.cosmolib.furniture.FurnitureOptions} default).
     */
    private final float seatHeight;

    // ------------------------------------------------------------------
    // Private constructor
    // ------------------------------------------------------------------

    private MultiBlockLayout(String furnitureId,
                              int[] bounds,
                              List<BlockPos> straight,
                              @Nullable List<BlockPos> diagonal,
                              boolean diagonalAutoGenerated,
                              List<BlockPos> straightSlabs,
                              @Nullable List<BlockPos> diagonalSlabs,
                              List<BlockPos> straightSeats,
                              @Nullable List<BlockPos> diagonalSeats,
                              float seatHeight) {
        this.furnitureId             = furnitureId;
        this.bounds                  = bounds;
        this.straightPositions       = Collections.unmodifiableList(new ArrayList<>(straight));
        this.diagonalPositions       = diagonal == null ? null : Collections.unmodifiableList(new ArrayList<>(diagonal));
        this.diagonalAutoGenerated   = diagonalAutoGenerated;
        this.straightSlabPositions   = Collections.unmodifiableList(new ArrayList<>(straightSlabs));
        this.diagonalSlabPositions   = diagonalSlabs == null ? null : Collections.unmodifiableList(new ArrayList<>(diagonalSlabs));
        this.straightSeatPositions   = Collections.unmodifiableList(new ArrayList<>(straightSeats));
        this.diagonalSeatPositions   = diagonalSeats == null ? null : Collections.unmodifiableList(new ArrayList<>(diagonalSeats));
        this.seatHeight              = seatHeight;
    }

    // ------------------------------------------------------------------
    // Factory methods
    // ------------------------------------------------------------------

    /**
     * Creates a layout with an automatically computed bounds and optional
     * auto-generated diagonal layout.
     *
     * <p>If the footprint is symmetric (width == depth), the diagonal list is
     * copied from {@code straight} automatically.
     * Otherwise, the diagonal falls back to straight at runtime until a proper
     * diagonal list is defined with {@link #of(String, List, List)}.
     *
     * @param id       registry path of the furniture block (e.g. {@code "ancient_arbor"})
     * @param straight occupied positions in rotation-0 space (block faces North / −Z), including anchor at (0,0,0)
     */
    public static MultiBlockLayout of(String id, List<BlockPos> straight) {
        int[] bounds = computeBounds(straight);
        boolean symmetric = bounds[0] == bounds[2];
        return new MultiBlockLayout(id, bounds, straight, null, symmetric,
                List.of(), null, List.of(), null, 5f / 16f);
    }

    /**
     * Creates a layout with an explicit diagonal position list.
     *
     * @param id       registry path of the furniture block
     * @param straight occupied positions for cardinal rotations (rotation 0, 2, 4, 6)
     * @param diagonal occupied positions for diagonal rotations (rotation 1, 3, 5, 7)
     */
    public static MultiBlockLayout of(String id, List<BlockPos> straight, List<BlockPos> diagonal) {
        int[] bounds = computeBounds(straight);
        return new MultiBlockLayout(id, bounds, straight, diagonal, false,
                List.of(), null, List.of(), null, 5f / 16f);
    }

    /**
     * Creates a layout with slab and/or seat positions.
     * Pass {@code null} for diagonal variants to auto-generate from straight.
     *
     * @param id            registry path of the furniture block
     * @param straight      occupied positions for cardinal rotations
     * @param diagonal      diagonal positions, or {@code null} to auto-generate
     * @param straightSlabs subset of {@code straight} that use a half-height (slab) hitbox
     * @param diagonalSlabs diagonal slab positions, or {@code null} to auto-generate
     * @param straightSeats subset of {@code straight} that are sittable seat positions
     * @param diagonalSeats diagonal seat positions, or {@code null} to auto-generate
     * @param seatHeight    height above the block origin at which the seat entity spawns
     */
    public static MultiBlockLayout of(String id,
                                       List<BlockPos> straight,
                                       @Nullable List<BlockPos> diagonal,
                                       List<BlockPos> straightSlabs,
                                       @Nullable List<BlockPos> diagonalSlabs,
                                       List<BlockPos> straightSeats,
                                       @Nullable List<BlockPos> diagonalSeats,
                                       float seatHeight) {
        int[] bounds = computeBounds(straight);
        boolean diagAuto = (diagonal == null);
        return new MultiBlockLayout(id, bounds, straight, diagonal, diagAuto,
                straightSlabs  != null ? straightSlabs  : List.of(), diagonalSlabs,
                straightSeats  != null ? straightSeats  : List.of(), diagonalSeats,
                seatHeight);
    }

    /**
     * Convenience overload: slab + seat positions, no explicit diagonal (auto-generated).
     * Equivalent to calling the 8-arg factory with {@code null} for both diagonal args.
     */
    public static MultiBlockLayout of(String id,
                                       List<BlockPos> straight,
                                       @Nullable List<BlockPos> diagonal,
                                       List<BlockPos> straightSlabs,
                                       @Nullable List<BlockPos> diagonalSlabs) {
        int[] bounds = computeBounds(straight);
        boolean diagAuto = (diagonal == null);
        return new MultiBlockLayout(id, bounds, straight, diagonal, diagAuto,
                straightSlabs != null ? straightSlabs : List.of(), diagonalSlabs,
                List.of(), null, 5f / 16f);
    }

    // ------------------------------------------------------------------
    // Rotation logic
    // ------------------------------------------------------------------

    /**
     * Returns the list of layout positions rotated to match the given 0–7 rotation value.
     *
     * <p>Even rotations (0, 2, 4, 6) use the straight list; odd rotations (1, 3, 5, 7)
     * use the diagonal list (falling back to straight when auto-generated).
     * Each pair of steps represents 90° clockwise.
     *
     * @param rotation block rotation state (0 = faces North, 2 = faces East,
     *                 4 = faces South, 6 = faces West; 1/3/5/7 = diagonals NE/SE/SW/NW).
     *                 "Faces North" means the block's front points North (−Z), which is
     *                 produced when the placing player was facing South (yaw = 0).
     * @return unmodifiable list of rotated positions, in the same coordinate space as
     *         the original lists (relative to anchor at ZERO)
     */
    public List<BlockPos> getRotatedPositions(int rotation) {
        boolean isDiagonal = (rotation % 2 != 0);
        List<BlockPos> base = isDiagonal
                ? (diagonalPositions != null ? diagonalPositions : straightPositions)
                : straightPositions;
        int cwSteps = isDiagonal ? (rotation - 1) / 2 : rotation / 2;
        if (cwSteps == 0) return base;
        return base.stream()
                .map(p -> rotateCW(p, cwSteps))
                .collect(Collectors.toUnmodifiableList());
    }

    /**
     * Returns the slab (half-height) positions rotated to match the given 0–7 rotation.
     * An empty list means no slab positions for this layout.
     *
     * @param rotation block rotation state (0–7); same convention as {@link #getRotatedPositions}
     * @return unmodifiable list of rotated slab positions
     */
    public List<BlockPos> getSlabPositions(int rotation) {
        boolean isDiagonal = (rotation % 2 != 0);
        List<BlockPos> base = isDiagonal
                ? (diagonalSlabPositions != null ? diagonalSlabPositions : straightSlabPositions)
                : straightSlabPositions;
        if (base.isEmpty()) return base;
        int cwSteps = isDiagonal ? (rotation - 1) / 2 : rotation / 2;
        if (cwSteps == 0) return base;
        return base.stream()
                .map(p -> rotateCW(p, cwSteps))
                .collect(Collectors.toUnmodifiableList());
    }

    /**
     * Returns the sittable seat positions rotated to match the given 0–7 rotation.
     * An empty list means no seat positions for this layout.
     *
     * @param rotation block rotation state (0–7); same convention as {@link #getRotatedPositions}
     * @return unmodifiable list of rotated seat positions
     */
    public List<BlockPos> getSeatingPositions(int rotation) {
        boolean isDiagonal = (rotation % 2 != 0);
        List<BlockPos> base = isDiagonal
                ? (diagonalSeatPositions != null ? diagonalSeatPositions : straightSeatPositions)
                : straightSeatPositions;
        if (base.isEmpty()) return base;
        int cwSteps = isDiagonal ? (rotation - 1) / 2 : rotation / 2;
        if (cwSteps == 0) return base;
        return base.stream()
                .map(p -> rotateCW(p, cwSteps))
                .collect(Collectors.toUnmodifiableList());
    }

    /**
     * Rotates a position {@code steps} times by 90° clockwise around the Y-axis.
     * Formula per step: (x, z) → (−z, x).
     */
    private static BlockPos rotateCW(BlockPos pos, int steps) {
        int x = pos.getX(), y = pos.getY(), z = pos.getZ();
        for (int i = 0; i < steps; i++) {
            int nx = -z;
            z  = x;
            x  = nx;
        }
        return new BlockPos(x, y, z);
    }

    // ------------------------------------------------------------------
    // Bounds computation
    // ------------------------------------------------------------------

    private static int[] computeBounds(List<BlockPos> positions) {
        if (positions.isEmpty()) return new int[]{1, 1, 1};
        int minX = positions.stream().mapToInt(BlockPos::getX).min().orElse(0);
        int maxX = positions.stream().mapToInt(BlockPos::getX).max().orElse(0);
        int minY = positions.stream().mapToInt(BlockPos::getY).min().orElse(0);
        int maxY = positions.stream().mapToInt(BlockPos::getY).max().orElse(0);
        int minZ = positions.stream().mapToInt(BlockPos::getZ).min().orElse(0);
        int maxZ = positions.stream().mapToInt(BlockPos::getZ).max().orElse(0);
        return new int[]{maxX - minX + 1, maxY - minY + 1, maxZ - minZ + 1};
    }

    // ------------------------------------------------------------------
    // Accessors
    // ------------------------------------------------------------------

    /** Registry path of the owning furniture block (e.g. {@code "ancient_arbor"}). */
    public String getFurnitureId()           { return furnitureId;           }

    /** [width, height, depth] bounding box computed from the straight positions. */
    public int[] getBounds()                 { return bounds.clone();         }

    /** Straight-rotation (cardinal) positions, as defined at rotation = 0 (North). */
    public List<BlockPos> getStraightPositions()  { return straightPositions; }

    /**
     * Diagonal-rotation positions, or {@code null} when auto-generated from straight.
     * Use {@link #getRotatedPositions} for runtime position lookups.
     */
    @Nullable
    public List<BlockPos> getDiagonalPositions() { return diagonalPositions; }

    /** {@code true} when the diagonal list was copied from straight (symmetric footprint). */
    public boolean isDiagonalAutoGenerated()  { return diagonalAutoGenerated; }

    /**
     * Straight (cardinal) slab positions in rotation-0 space.
     * Empty list when no slab positions are defined.
     */
    public List<BlockPos> getStraightSlabPositions() { return straightSlabPositions; }

    /**
     * Diagonal slab positions in rotation-1 space, or {@code null} when auto-generated
     * from {@link #getStraightSlabPositions}.
     * Use {@link #getSlabPositions} for runtime lookups.
     */
    @Nullable
    public List<BlockPos> getDiagonalSlabPositions() { return diagonalSlabPositions; }

    /** Straight (cardinal) seat positions in rotation-0 space. Empty if none defined. */
    public List<BlockPos> getStraightSeatPositions()  { return straightSeatPositions; }

    /**
     * Diagonal seat positions in rotation-1 space, or {@code null} when auto-generated
     * from {@link #getStraightSeatPositions}.
     * Use {@link #getSeatingPositions} for runtime lookups.
     */
    @Nullable
    public List<BlockPos> getDiagonalSeatPositions()  { return diagonalSeatPositions; }

    /**
     * Sit height in blocks above each seat position's origin.
     * Default {@code 5/16} matches {@link net.meh.cosmolib.furniture.FurnitureOptions} default.
     */
    public float getSeatHeight()                       { return seatHeight; }

    // ------------------------------------------------------------------
    // JSON serialization
    // ------------------------------------------------------------------

    /**
     * Serializes this layout to a {@link JsonObject} using the canonical format:
     * <pre>{@code
     * {
     *   "furniture_id": "ancient_arbor",
     *   "bounds": [3, 3, 1],
     *   "diagonal_auto_generated": false,
     *   "straight": [[0,0,0],[1,0,0],...],
     *   "diagonal": [[0,0,0],[1,0,0],...]
     * }
     * }</pre>
     */
    public JsonObject toJson() {
        JsonObject obj = new JsonObject();
        obj.addProperty("furniture_id", furnitureId);

        JsonArray boundsArr = new JsonArray();
        for (int b : bounds) boundsArr.add(b);
        obj.add("bounds", boundsArr);

        obj.addProperty("diagonal_auto_generated", diagonalAutoGenerated);
        obj.add("straight", posListToJson(straightPositions));

        // Always write diagonal (even if auto-generated, write the effective list)
        List<BlockPos> diag = (diagonalPositions != null) ? diagonalPositions : straightPositions;
        obj.add("diagonal", posListToJson(diag));

        // Only write slab arrays when there are slab positions
        if (!straightSlabPositions.isEmpty()) {
            obj.add("straight_slabs", posListToJson(straightSlabPositions));
        }
        if (diagonalSlabPositions != null && !diagonalSlabPositions.isEmpty()) {
            obj.add("diagonal_slabs", posListToJson(diagonalSlabPositions));
        }

        // Only write seat arrays and height when there are seat positions
        if (!straightSeatPositions.isEmpty()) {
            obj.add("straight_seats", posListToJson(straightSeatPositions));
            obj.addProperty("seat_height", seatHeight);
        }
        if (diagonalSeatPositions != null && !diagonalSeatPositions.isEmpty()) {
            obj.add("diagonal_seats", posListToJson(diagonalSeatPositions));
        }

        return obj;
    }

    /** Converts this layout to a pretty-printed JSON string. */
    public String toJsonString() {
        return GSON.toJson(toJson());
    }

    /**
     * Deserializes a {@link MultiBlockLayout} from a JSON object.
     *
     * @param obj the root JSON object (as written by {@link #toJson()})
     * @return the deserialized layout
     * @throws JsonParseException if required fields are missing or malformed
     */
    public static MultiBlockLayout fromJson(JsonObject obj) {
        String id = obj.get("furniture_id").getAsString();
        boolean diagAuto = obj.has("diagonal_auto_generated")
                && obj.get("diagonal_auto_generated").getAsBoolean();

        List<BlockPos> straight = jsonToPosList(obj.getAsJsonArray("straight"));
        List<BlockPos> diagonal = obj.has("diagonal")
                ? jsonToPosList(obj.getAsJsonArray("diagonal"))
                : null;

        List<BlockPos> straightSlabs = obj.has("straight_slabs")
                ? jsonToPosList(obj.getAsJsonArray("straight_slabs")) : List.of();
        List<BlockPos> diagonalSlabs = obj.has("diagonal_slabs")
                ? jsonToPosList(obj.getAsJsonArray("diagonal_slabs")) : null;

        List<BlockPos> straightSeats = obj.has("straight_seats")
                ? jsonToPosList(obj.getAsJsonArray("straight_seats")) : List.of();
        List<BlockPos> diagonalSeats = obj.has("diagonal_seats")
                ? jsonToPosList(obj.getAsJsonArray("diagonal_seats")) : null;
        float parsedSeatHeight = obj.has("seat_height")
                ? obj.get("seat_height").getAsFloat() : 5f / 16f;

        int[] bounds = computeBounds(straight);

        if (diagAuto || diagonal == null) {
            return new MultiBlockLayout(id, bounds, straight, null, true,
                    straightSlabs, diagonalSlabs, straightSeats, diagonalSeats, parsedSeatHeight);
        }
        return new MultiBlockLayout(id, bounds, straight, diagonal, false,
                straightSlabs, diagonalSlabs, straightSeats, diagonalSeats, parsedSeatHeight);
    }

    // ------------------------------------------------------------------
    // JSON helpers
    // ------------------------------------------------------------------

    private static JsonArray posListToJson(List<BlockPos> positions) {
        JsonArray arr = new JsonArray();
        for (BlockPos pos : positions) {
            JsonArray p = new JsonArray();
            p.add(pos.getX());
            p.add(pos.getY());
            p.add(pos.getZ());
            arr.add(p);
        }
        return arr;
    }

    private static List<BlockPos> jsonToPosList(JsonArray arr) {
        List<BlockPos> list = new ArrayList<>();
        for (JsonElement el : arr) {
            JsonArray p = el.getAsJsonArray();
            list.add(new BlockPos(p.get(0).getAsInt(), p.get(1).getAsInt(), p.get(2).getAsInt()));
        }
        return list;
    }

    // ------------------------------------------------------------------
    // Object overrides
    // ------------------------------------------------------------------

    @Override
    public String toString() {
        return "MultiBlockLayout{id='" + furnitureId + "', bounds="
                + Arrays.toString(bounds) + ", straight=" + straightPositions.size()
                + " positions}";
    }
}
