package net.meh.cosmolib.toolskin.client;

import net.meh.cosmolib.CosmoLib;
import net.meh.cosmolib.toolskin.OriginalItemTooltipComponent;
import net.meh.cosmolib.toolskin.ToolSkinType;
import net.minecraft.client.renderer.texture.TextureAtlas;
import net.minecraft.client.renderer.texture.atlas.sources.SingleFile;
import net.minecraft.client.resources.model.BakedModel;
import net.minecraft.client.resources.model.ModelResourceLocation;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.ModelEvent;
import net.neoforged.neoforge.client.event.RegisterClientTooltipComponentFactoriesEvent;
import net.neoforged.neoforge.client.event.RegisterSpriteSourceTypesEvent;

import java.util.ArrayList;
import java.util.Map;

/**
 * Mod-bus client event handler for the Tool Skin rendering system.
 *
 * <p>Hooks into {@link ModelEvent.ModifyBakingResult} to wrap the baked model of
 * every item that can receive a tool skin with {@link ToolSkinAwareBakedModel}.
 * The wrapper intercepts item-stack rendering at resolve time and swaps in a
 * {@link ToolSkinModel} when the stack carries a
 * {@link net.meh.cosmolib.toolskin.ToolSkinData} component.
 *
 * <p><b>Texture stitching</b>: skin textures are stitched into the block atlas
 * automatically because each {@link net.meh.cosmolib.toolskin.ToolSkinItem} token
 * model JSON (generated by
 * {@link net.meh.cosmolib.toolskin.datagen.ToolSkinItemModelProvider}) references
 * the skin texture as {@code layer1}.  MC stitches all model-referenced textures
 * into the block atlas during resource loading, so no manual stitching event is
 * required provided dependent mods supply the model JSON.
 */
@EventBusSubscriber(modid = CosmoLib.MOD_ID, bus = EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
public final class ToolSkinClientEventHandler {

    private ToolSkinClientEventHandler() {}

    /**
     * Registers the {@link ClientOriginalItemTooltipComponent} factory so that MC's
     * tooltip pipeline can convert the common-side {@link OriginalItemTooltipComponent}
     * (injected by {@link net.meh.cosmolib.mixin.ItemStackTooltipMixin}) into the
     * client-side renderer that draws the original item icon.
     */
    @SubscribeEvent
    public static void registerTooltipFactories(RegisterClientTooltipComponentFactoriesEvent event) {
        event.register(OriginalItemTooltipComponent.class,
                ClientOriginalItemTooltipComponent::of);
    }


    /**
     * Wraps the baked model of every registered item whose {@link ToolSkinType} is
     * known with {@link ToolSkinAwareBakedModel}.  This covers all vanilla tool
     * variants as well as any modded items registered before this event fires.
     *
     * <p>Iterates {@link BuiltInRegistries#ITEM}, tests each item via
     * {@link ToolSkinType#fromItem}, and replaces the corresponding
     * {@link ModelResourceLocation} entry in the models map.
     */
}
